-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Auto.Object exposing (CounterState(..), User(..))


type CounterState
    = CounterState


type User
    = User
