-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object exposing (..)


type CounterState
    = CounterState


type User
    = User
