-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Query exposing (..)

import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.Operation exposing (RootQuery)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


{-| Select fields to build up a top-level query. The request can be sent with
functions from `Graphqelm.Http`.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) RootQuery
selection constructor =
    Object.selection constructor


exchangeCredentialsForToken : { email : String, password : String } -> Field (Maybe String) RootQuery
exchangeCredentialsForToken requiredArgs =
    Object.fieldDecoder "exchangeCredentialsForToken" [ Argument.required "email" requiredArgs.email Encode.string, Argument.required "password" requiredArgs.password Encode.string ] (Decode.string |> Decode.maybe)


{-| Who am I?
-}
whoami : SelectionSet decodesTo Api.Object.User -> Field (Maybe decodesTo) RootQuery
whoami object =
    Object.selectionField "whoami" [] object (identity >> Decode.maybe)
