-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Auto.Object.User exposing (email, id, name)

import Auto.InputObject
import Auto.Interface
import Auto.Object
import Auto.Scalar
import Auto.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


email : SelectionSet String Auto.Object.User
email =
    Object.selectionForField "String" "email" [] Decode.string


id : SelectionSet Int Auto.Object.User
id =
    Object.selectionForField "Int" "id" [] Decode.int


name : SelectionSet String Auto.Object.User
name =
    Object.selectionForField "String" "name" [] Decode.string
